#!/bin/bash
# Automated Directory Cleanup Script
# Generated by directory_cleanup_plan.py

echo "=== Directory Cleanup Script ==="
echo "Starting cleanup process..."

# Create backup directory
BACKUP_DIR="/mnt/d/multiagent-system/cleanup_backup_$(date +%Y%m%d_%H%M%S)"
mkdir -p "$BACKUP_DIR"
echo "Backup directory created: $BACKUP_DIR"


# Move duplicate files to backup
mv "/mnt/d/multiagent-system/analysis_results_20250629_202843.json" "$BACKUP_DIR/"
mv "/mnt/d/multiagent-system/analysis_results_20250629_202633.json" "$BACKUP_DIR/"
mv "/mnt/d/multiagent-system/analysis_results_20250629_202609.json" "$BACKUP_DIR/"
mv "/mnt/d/multiagent-system/e_based_logic_verification_v2.csv" "$BACKUP_DIR/"
mv "/mnt/d/multiagent-system/e_based_logic_verification.csv" "$BACKUP_DIR/"
mv "/mnt/d/multiagent-system/med_error_analysis_v2.py" "$BACKUP_DIR/"
mv "/mnt/d/multiagent-system/med_error_analysis.py" "$BACKUP_DIR/"
mv "/mnt/d/multiagent-system/verify_e_based_logic_v2.py" "$BACKUP_DIR/"
mv "/mnt/d/multiagent-system/verify_e_based_logic.py" "$BACKUP_DIR/"
mv "/mnt/d/DN001_TF/2025_G00(DT1878,1899,1909)/Sessions/20250629/Batch_20250629_DT1878_MEDx_analysis_corrected.m" "$BACKUP_DIR/"
mv "/mnt/d/DN001_TF/2025_G00(DT1878,1899,1909)/Sessions/20250629/visualize_timecourse_improved.m" "$BACKUP_DIR/"
mv "/mnt/d/DN001_TF/2025_G00(DT1878,1899,1909)/Sessions/20250629/visualize_timecourse_updated.m" "$BACKUP_DIR/"
mv "/mnt/d/DN001_TF/2025_G00(DT1878,1899,1909)/Sessions/20250629/visualize_timecourse.m" "$BACKUP_DIR/"

# Move obsolete files to backup
mv "/mnt/d/multiagent-system/behavior_plot_verification.py" "$BACKUP_DIR/"
mv "/mnt/d/multiagent-system/bh_timing_emergency_report.md" "$BACKUP_DIR/"
mv "/mnt/d/multiagent-system/critical_emergency_report.txt" "$BACKUP_DIR/"
mv "/mnt/d/multiagent-system/dt1899_protocol_bug_verification.py" "$BACKUP_DIR/"
mv "/mnt/d/multiagent-system/emergency_timing_check.m" "$BACKUP_DIR/"
mv "/mnt/d/multiagent-system/hit_miss_logic_emergency_analysis.md" "$BACKUP_DIR/"
mv "/mnt/d/multiagent-system/test_visualization.m" "$BACKUP_DIR/"
mv "/mnt/d/multiagent-system/tmp/test_invalid_format.txt" "$BACKUP_DIR/"
mv "/mnt/d/DN001_TF/2025_G00(DT1878,1899,1909)/Sessions/20250629/lick_timing_verification.py" "$BACKUP_DIR/"

echo "Cleanup completed. Files backed up to: $BACKUP_DIR"
